/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StartPurchasing_form.java
 *
 * Created on 12 Jun, 2015, 6:41:08 PM
 */

package shopping_management;

/**
 *
 * @author Parmood
 */
public class StartPurchasing_form extends javax.swing.JFrame {
int Memcode;
    /** Creates new form StartPurchasing_form */
    public StartPurchasing_form() {
        initComponents();
    }
    public StartPurchasing_form(int mno) {
        Memcode=mno;
        initComponents();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choose your Appliance");

        jPanel1.setBackground(new java.awt.Color(189, 189, 242));

        jList1.setBackground(new java.awt.Color(194, 194, 249));
        jList1.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/sony xperia.jpg")))); // NOI18N
        jList1.setFont(new java.awt.Font("Arial", 2, 36));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Air Conditioner", "Laptop ", "SmartPhones", "Television", "Refrigerator", "Microwave Oven" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
    if(jList1.getSelectedIndex()==0)
    {
    new Air_Conditioner(Memcode).setVisible(true);
    setVisible(false);
    }
    if(jList1.getSelectedIndex()==1)
    {
    new Laptop(Memcode).setVisible(true);
    setVisible(false);
    }
    if(jList1.getSelectedIndex()==2)
    {
    new SmartPhones(Memcode).setVisible(true);
    setVisible(false);
    }
    if(jList1.getSelectedIndex()==3)
    {
    new Television(Memcode).setVisible(true);
    setVisible(false);
    }
    if(jList1.getSelectedIndex()==4)
    {
    new Refrigerator(Memcode).setVisible(true);
    setVisible(false);
    }
    if(jList1.getSelectedIndex()==5)
    {
    new Microwave_oven(Memcode).setVisible(true);
    setVisible(false);
    }
    }//GEN-LAST:event_jList1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPurchasing_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
